name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git stash --include-untracked
        git checkout -B gh-pages
        git stash pop
        git add main.pdf
        git commit -m "add pdf"
        git fetch origin gh-pages
        git push --force-with-lease origin gh-pages